version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Etienne1!
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Map to a different port on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: Etienne1!
      DB_NAME: postgres
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  postgres_data:
